### ISSUE TITLE
Better integration of known issues 

### ISSUE THREAD

**Issue by hazel-nut** [digitalocean/navigators-guide#35]
these known issues should be integrated at the point in the walkthrough where the user might make these mistakes or encounter those issues.

-----

These are known issues that you'll want to watch for if you configure your variables manually:

* A couple additional items to look out for when setting up these passwords, including your auth salts, these passwords are being run through the jinja templating system and there a few character combinations that can cause errors since they are jinja delimeters. So watch out for the following character combos:
{% raw %}
  * {%
  * {{
  * {#
{% endraw %}

* Using a dollar sign `$` in your Galera passwords could cause the script that assists with the health check feature of HAProxy may not see the database as online:

  * vault_galera_root_password
  * vault_galera_sys_maint_password
  * vault_galera_clustercheck_password

**Comment by jonschwenn** [comment]
Added this to put it at the end of the book:  https://github.com/digitalocean/navigators-guide/blob/master/book/knownissues.md
